[env:esp32dev]
platform = espressif32 @ 6.4.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

build_flags =
    ; --- TFT ST7789 SPI 240x320 (shared with nRF24 radios) ---
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=21
    -D TFT_RST=14
    -D TFT_BL=-1
    -D TFT_INVERSION_OFF=1
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=6000000
    -D SUPPORT_TRANSACTIONS=1

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    nrf24/RF24 @ ^1.4.10
    bblanchon/ArduinoJson@^7.0.4
    mikalhart/TinyGPSPlus @ ^1.1.0
