#ifndef CAROUSEL_ICON_ASSETS_H
#define CAROUSEL_ICON_ASSETS_H

#include <Arduino.h>

static constexpr int CAROUSEL_ICON_SIZE = 72;
static constexpr int CAROUSEL_ICON_PIXELS = CAROUSEL_ICON_SIZE * CAROUSEL_ICON_SIZE;
static constexpr uint16_t CAROUSEL_ICON_TRANSPARENT = 0x0001;

extern const uint16_t CAROUSEL_ICON_WIFI[CAROUSEL_ICON_PIXELS] PROGMEM;
extern const uint16_t CAROUSEL_ICON_RADIO[CAROUSEL_ICON_PIXELS] PROGMEM;
extern const uint16_t CAROUSEL_ICON_BLUETOOTH[CAROUSEL_ICON_PIXELS] PROGMEM;
extern const uint16_t CAROUSEL_ICON_MONITOR[CAROUSEL_ICON_PIXELS] PROGMEM;
extern const uint16_t CAROUSEL_ICON_SYSTEM[CAROUSEL_ICON_PIXELS] PROGMEM;

const uint16_t* getCarouselIcon(uint8_t index);

#endif
